### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by speedAccount** [Inder00/FunnyWeb#1]
czesc, w którym pliku wpisać dane do mysql?

**Comment by speedAccount** [comment]
@Inder00

**Comment by Inder00** [comment]
Witaj,
Instalator sam przeprowadzi Cię przez instalacje.
A jeżeli chcesz sam podpiąc mysql bez wcześniej stworzysz tabelek to robisz na własną odpowiedzialnośc. Wszystko masz w /conf_global.php

**Comment by speedAccount** [comment]
@Inder00 
Dzięki, a jak włączyć ten instalator jeżeli się nie myle to jest plik install.php, dałem to na maszynę vps url z plikiem install.php "178.33.255.47/install.php", bo nie odpala się instalator tylko kod jest

**Comment by Inder00** [comment]
apt-get install php php-curl

**Comment by speedAccount** [comment]
@Inder00 
Wpisałem i nadal ten kod jest

**Comment by speedAccount** [comment]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php
E: Unable to locate package php-curl

**Comment by Inder00** [comment]
zaintaluj php i przeladuj apache2

**Comment by Inder00** [comment]
apt-get update && apt-get upgrade
potem
apt-get install php

**Comment by speedAccount** [comment]
@Inder00 
nadal kod, może dałbym ci na pw dane do vpsa i to zrobisz za mnie?

**Comment by speedAccount** [comment]
@Inder00 
dobra, już zrobilem dzięki za pomoc

**Comment by speedAccount** [comment]
@Inder00 
ahh te błędy, kolejny bląd po zainstalowaniu pisze tam: Aby się zalogować do panelu uzyj tego linku.
klikam w ten link i wyskakuje: The requested URL /admin/install.php was not found on this server.

**Comment by speedAccount** [comment]
@Inder00

**Comment by Inder00** [comment]
wyslij mi dane do VPS na maila **inder00@wp.pl**

**Comment by Inder00** [comment]
Widze, że sb poradziłeś

**Comment by speedAccount** [comment]
@Inder00 
Sory ze nie pisałem ale kompletnie zapomniałem już wysyłam dane
