### ISSUE TITLE
Problem ze ścieżkami

### ISSUE THREAD

**Issue by Ryderek** [Inder00/FunnyWeb#7]
Witam,
Zainstalowałem stronę na VPS'ie. System: Debian 10.
Skrypt połączył się z bazą, utworzył wszystkie potrzebne tabele, ale po wejściu w ścieżkę admina wciąż przekierowuje do /install.php przez co strona w ogóle nie funkcjonuje... To samo, jak wchodzę w /index.php - ponownie wywala instalator i tak w kółko. Połączenie z bazą działa na 100%, FunnyGuilds pobiera i zapisuje dane bez problemu. 

Jakieś pomysły w czym problem?

**Comment by Inder00** [comment]
Zapraszam na kontakt mailowy inder00@wp.pl
